notifications:
  email:
    - deepdive-dev@lists.stanford.edu
language:
  - scala
  - python
scala:
  - "2.10.5"
sbt_args:
jdk:
  - openjdk7
  - oraclejdk7
python:
  - "2.7"
services:
  - postgresql

env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=
    - PGPORT=5432
    - PGHOST=localhost
    - DBNAME=deepdive_test

install:
  - make install
script:
  - make test

  # Install linkchecker
  - sudo pip install linkchecker --use-mirrors
  # Install jekyll for "make serve" local hosting
  - gem install jekyll
  - make -C doc/ serve  # serve to localhost
  - sleep 3 # give Web server some time to bind to sockets, etc
  # Check both localhost and website
  - bash ./src/test/bash/linkcheck.sh http://localhost:4000/
  - bash ./src/test/bash/linkcheck.sh http://deepdive.stanford.edu/
after_success:
  - sbt coveralls
