language: 
  - scala
  - python
scala:
  - "2.10.3"
python:
  - "2.7"
install: 
  # Install linkchecker
  - sudo pip install linkchecker --use-mirrors
  # Install jekyll for "make serve" local hosting
  - gem install jekyll
jdk:
  - openjdk7
  - oraclejdk7
sbt_args:
services:
  - postgresql
env: 
  global:
    - PGUSER=postgres
    - PGPASSWORD=""
    - PGPORT=5432
    - PGHOST=localhost
    - DBNAME=deepdive_test
    - LD_LIBRARY_PATH=/tmp/dw_linux/lib/dw_linux/lib:/tmp/dw_linux/lib/dw_linux/lib64
notifications:
  email:
    - zifeishan@gmail.com
before_script:
  - unzip lib/dw_linux.zip -d /tmp/
  - psql -c 'create database deepdive_test;' -U postgres
  # - psql -c 'create database deepdive_test;' -U postgres
# script: "./test.sh"
