source:      .
safe:        true
baseurl: http://www.stanford.edu/~zifei/deepdive
# TODO let's consider using redcarpet, as it seems to be the most similar to GitHub-flavored Markdown
markdown:    redcarpet
exclude:
  - deploy.sh
  - host.sh
  - params.json
  - "*.graffle"
  - Makefile
